### ISSUE TITLE
npm releases have gone missing

### ISSUE THREAD

**Issue by mike-lang** [tanx/hoodiecrow#3]
Hi!  

I've been using the hoodiecrow nodeJS module for a while now as part of the regression test suite for my nodeJS system and today discovered that the versions we depend upon seem to be no longer available from npm.  Was this done in error?  It appears that only version `1.3.27` is now available from npm and it's unclear exactly what code this represents as the release labels in this github repo end at `v1.2.2`.  Please advise.

Thanks for developing this module, its been very helpful to us.

**Comment by tanx** [comment]
Hi Mike,

you're refering to https://github.com/andris9/hoodiecrow

This project just adopted the name hoodiecrow.

**Comment by mike-lang** [comment]
Ok. Thanks.
